_target_: src.models.cifar100_module.cifar100Module

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 1e-2
  momentum: 0.9
  weight_decay: 1e-4

scheduler: null
net:
  _target_: timm.create_model
  model_name: 'swin_large_patch4_window7_224.ms_in22k'
  pretrained: True
  num_classes: 100

aug: randaug_mixup
model_name: 'swin'

# compile model for faster training with pytorch 2.0
compile: false
