_target_: src.models.cifar100_module.cifar100Module

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler: null
net:
  _target_: timm.create_model
  model_name: 'resnet50.a1_in1k'
  pretrained: False

aug: mixup
model_name: 'resnet50'

# compile model for faster training with pytorch 2.0
compile: false
