_target_: src.models.randcutmix_module.RandcutmixModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.wide_resnet.Wide_ResNet
  depth: 28
  widen_factor: 10
  dropout_rate: 0
  num_classes: 200
  dataset: tinyImage

# compile model for faster training with pytorch 2.0
compile: false
