_target_: src.models.randcutmix_module.RandcutmixModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler: null
net:
  _target_: src.models.components.wide_resnet.Wide_ResNet
  depth: 28
  widen_factor: 10
  dropout_rate: 0
  num_classes: 200
  dataset: tinyImage

aug: randcutmix
model_name: wide_resnet

# compile model for faster training with pytorch 2.0
compile: false
