_target_: src.models.randcutmix_module.RandcutmixModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler: null
net:
  _target_: timm.create_model
  model_name: 'resnext101_32x8d'
  pretrained: False
  num_classes: 200

aug: baseline
model_name: 'resnext101'

# compile model for faster training with pytorch 2.0
compile: false
